export default {
  SUCCESS_RECIPES_REQUEST: "SUCCESS_RECIPES_REQUEST",
  SET_RECIPES_LOADING: "SET_RECIPES_LOADING",
  SET_RECIPES_QUERY: "SET_RECIPES_QUERY",
  SET_RECIPES_PREFERENCES: "SET_RECIPES_PREFERENCES"
};
