export default {
  SET_USER_LOADING: "SET_USER_LOADING",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_USER_ERROR: "SET_USER_ERROR",
  SET_USER_STATUS: "SET_USER_STATUS",
  SET_ALL_USERS: "SET_ALL_USERS"
};
